modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="${issue_tracker_url}" 



[[mods]] 

modId="${electrodynamics_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="${homepage_url}"

logoFile="${logo_file}"

credits="${mod_credits}"

authors="${mod_authors}" 

description="${mod_desc}"

[[mixins]]

config="${mod_id}.mixins.json"