modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/aurilisdev/Electrodynamics/issues" 



[[mods]] 

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://github.com/aurilisdev/Electrodynamics"

logoFile="electrodynamics.png"

credits="${credits}"

authors="${mod_authors}" 

description="${mod_description}"

[[mixins]]

config="${mod_id}.mixins.json"